<?php
/**
 * User: alanlucian
 * Date: 2/4/14
 * Time: 2:03 PM
 */

class ARMPerlModule extends ARMBaseModuleAbstract {


	/**
	 * @var ARMPerlConfigVO
	 */
	protected $_config ;

	public function setConfig($ob) {

		parent::setConfig($ob);


		if(!is_dir($this->_config->perl_lib_path)){
			ARMDebug::error("ARMPerlModule - perl_lib_path is not a valid directory");
			ARMDebug::dump($this->_config);
			die;
		}
		set_include_path(get_include_path() . PATH_SEPARATOR . $this->_config->perl_lib_path );
	}


	public function load( $class_name ){
		$pathAsArray = explode("_" , $class_name ) ;
		include( implode("/", $pathAsArray ) . ".php" ) ;

	}

	/**
	 * @param null $alias
	 * @param bool $useDefaultIfNotFound
	 * @return ARMPerlModule
	 */
	public static function getInstance($alias = NULL, $useDefaultIfNotFound = FALSE) {
		return parent::getInstance($alias, $useDefaultIfNotFound); // TODO: Change the autogenerated stub
	}


}