<?php
/**
 * 
 * User: renatomiawaki
 * Date: 11/25/13
 * 
 */

class ARMDictionaryModule extends ARMBaseModuleAbstract{
	/**
	 * @var ARMDictionary
	 */
	public  $dictio ;

	public function __construct() {
		$this->dictio = new ARMDictionary() ;
	}

	/**
	 * @return ARMDictionaryModule
	 */
	public static function getDefaultInstance(){
		return parent::getDefaultInstance();
	}

	/**
	 * @return ARMDictionaryModule
	 */
	public static function getInstance( $alias = self::DEFAULT_GLOBAL_ALIAS ) {
		$instance = parent::getInstance( $alias ) ;
		if( $alias != self::DEFAULT_GLOBAL_ALIAS ){
			//pega o default tb
			$rootInstance = parent::getInstance( self::DEFAULT_GLOBAL_ALIAS ) ;

			/* @var $rootInstance ARMDictionaryModule  */
			/* @var $instance ARMDictionaryModule  */
			$dataOfDefault  = $rootInstance->dictio->getData() ;

			$instance->dictio->mergeData( $dataOfDefault ) ;
		}
		return $instance ;
	}
	/**
	 * @override
	 */
	public static function getConfigClassName(){

		return "ARMDictionaryConfigVO" ;
	}

	public function getParsedConfigData( $configResult ){
		$configVO = new ARMDictionaryConfigVO() ;
		$configVO->parseObject( $configResult ) ;
		return $configVO ;
	}


	/**
	 * @param ARMDictionaryConfigVO $ob
	 */
	public function setConfig( $ob ){
		if( is_object( $ob ) ){
			$this->dictio->mergeData( ( array ) $ob , FALSE ) ;
		}
		parent::setConfig($ob); // TODO: Change the autogenerated stub
	}


}