<?php
/**
 * 
 * User: renatomiawaki
 * Date: 11/25/13
 * 
 */

class ARMHtmlFormMakerConfigVO extends ARMAutoParseAbstract{
	public $action ;
	public $method ;

	/**
	 * @override
	 */
	public function parseObject($object){
		ARMDebug::print_r( $object ) ;
		return parent::parseObject($object); // TODO: Change the autogenerated stub
	}

}