<?php
	/**
	* created by ARMModuleMaker ( automated system )
	* Please, change this file
	* don't change ARMBaseARMGenericParameterModuleAbstract class
	*
	* ARMBaseARMGenericParameterModuleAbstract
	* @date 18/03/2014 01:03:21
	*/

class ARMGenericParameterModule extends ARMBaseARMGenericParameterModuleAbstract {
	//put your changes and rewrited methods here
	//Good developers always comment theirs code


	public function addParameter( $ref_name , $ref_id , $param_value, $param_name = NULL ){

		$DAO = ARMGenericParameterModelGateway::getInstance()->getDAO();
		$VO = $this->getBasicVO($ref_name , $ref_id , $param_name );
		$VO->data = $param_value ;

		return $this->commitVO( $VO );

	}

	public function setParameter( $ref_name , $ref_id, $param_value , $param_name = NULL){
		$DAO = ARMGenericParameterModelGateway::getInstance()->getDAO();
		$VO = $this->getBasicVO($ref_name , $ref_id , $param_name );


		$returnData = $DAO->deleteByVO( $VO ) ;

		$VO->data = $param_value ;

		return $this->commitVO( $VO );

	}


	public function getParameter( $ref_name , $ref_id,  $param_name = NULL ){

		$DAO = ARMGenericParameterModelGateway::getInstance()->getDAO();
		$VO = $this->getBasicVO($ref_name , $ref_id , $param_name );

		$returnResult = new ARMReturnResultVO();

		$returnData = $DAO->selectByVO( $VO ) ;
		if( $returnData->hasResult() ){
			$returnResult->result  = $returnData->result ;
		}
		$returnResult->success = TRUE ;

		return $returnResult ;
	}

	/**
	 * Common commit feature
	 * @param $VO
	 * @return ARMReturnResultVO
	 */
	protected function commitVO( $VO ){

		$DAO = ARMGenericParameterModelGateway::getInstance()->getDAO();
		$returnData = $DAO->commitVO( $VO );

		$returnResult = new ARMReturnResultVO();

		if(!$returnData->success){
			$returnResult->addMessage( $returnData->error_message );
			return $returnResult ;
		}
		$returnResult->success = TRUE;
		$returnResult->result = $VO ;

		return $returnResult;
	}

	/**
	 * @param $ref_name
	 * @param $ref_id
	 * @param null $param_name
	 * @return ARMGenericParameterVO
	 */
	protected function getBasicVO( $ref_name , $ref_id , $param_name = NULL ){

		$VO = ARMGenericParameterModelGateway::getInstance()->getVO();

		$VO->active = 1 ;
		$VO->ref_id = $ref_id ;
		$VO->ref_name = $ref_name ;
		$VO->data = $param_name ;

		return $VO ;
	}

	/**
	 * @param null|string $alias
	 * @param bool $useDefaultIfNotFound
	 * @return ARMGenericParameterModule
	 */
	public static function getInstance($alias = self::DEFAULT_GLOBAL_ALIAS, $useDefaultIfNotFound = FALSE)
	{
		return parent::getInstance($alias, $useDefaultIfNotFound); // TODO: Change the autogenerated stub
	}


}